stages:
  - lint
  - build
  - deploy

variables:
  NODE_VERSION: 18.14.2

before_script:
  - apt-get update && apt-get install -y curl
  - curl -sS https://get.pnpm.io/install.sh | sh -s
  - pnpm install

lint: 
  stage: lint
  image: node:$NODE_VERSION
  script: 
    - pnpm run format

build-ts:
  stage: build
  image: node:$NODE_VERSION
  script:
    - pnpm run build
    - pnpm run type-check
  only:
    - merge_requests
    - main

deploy:
  stage: deploy
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t my-image:$CI_COMMIT_SHA -t my-image:latest .
    - docker push my-image:$CI_COMMIT_SHA
    - docker push my-image:latest
