stages:
  - lint
  - build
  - deploy

variables:
  NODE_VERSION: 18.14.2

# before_script:
#   - export SHELL=/bin/bash
#   - corepack enable
#   - corepack prepare pnpm@latest --activate
#   - pnpm install

# lint: 
#   stage: lint
#   image: node:$NODE_VERSION
#   script: 
#     - pnpm run format

# build-ts:
#   stage: build
#   image: node:$NODE_VERSION
#   script:
#     - pnpm run build
#     - pnpm run type-check
#   only:
#     - merge_requests
#     - main

deploy:
  stage: deploy
  image: docker:27.5.1
  services:
    - docker:27.5.1-dind
  script:
    - docker info
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t $DOCKER_USERNAME/tg-web-app:$CI_COMMIT_SHA -t $DOCKER_USERNAME/tg-web-app:latest .
    - docker push $DOCKER_USERNAME/tg-web-app:$CI_COMMIT_SHA
    - docker push $DOCKER_USERNAME/tg-web-app:latest
