stages:
  - lint
  - build
  - deploy

variables:
  NODE_VERSION: 18.14.2

before_script:
  - export SHELL=/bin/bash
  # Устанавливаем curl и bash, если их нет
  - apk add --no-cache curl bash
  # Устанавливаем nvm
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
  - source ~/.nvm/nvm.sh  # Загружаем nvm
  - nvm install $NODE_VERSION  # Устанавливаем нужную версию Node.js
  - nvm use $NODE_VERSION  # Активируем установленную версию
  - npm install -g corepack  # Устанавливаем corepack через npm
  - corepack enable
  - corepack prepare pnpm@latest --activate
  - pnpm install

# lint: 
#   stage: lint
#   image: node:$NODE_VERSION
#   script: 
#     - pnpm run format

# build-ts:
#   stage: build
#   image: node:$NODE_VERSION
#   script:
#     - pnpm run build
#     - pnpm run type-check
#   only:
#     - merge_requests
#     - main

deploy:
  stage: deploy
  image: docker:27.5.1
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t my-image:$CI_COMMIT_SHA -t my-image:latest .
    - docker push my-image:$CI_COMMIT_SHA
    - docker push my-image:latest
