stages:
  - lint
  - build
  - deploy

variables:
  NODE_VERSION: 18.14.2

before_script:
  - export SHELL=/bin/bash
  - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -  # Установим Node.js (если не установлен)
  - apt-get update && apt-get install -y curl gnupg  # Установим curl и gnupg, если нужно
  - curl -fsSL https://github.com/npm/corepack/releases/latest/download/corepack-v0.18.0-linux-x64.tar.gz | tar -xz -C /usr/local/bin  # Установка corepack
  - corepack enable
  - corepack prepare pnpm@latest --activate
  - pnpm install

lint: 
  stage: lint
  image: node:$NODE_VERSION
  script: 
    - pnpm run format

build-ts:
  stage: build
  image: node:$NODE_VERSION
  script:
    - pnpm run build
    - pnpm run type-check
  only:
    - merge_requests
    - main

deploy:
  stage: deploy
  image: docker:20.10.7
  script:
    - docker --version
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t my-image:$CI_COMMIT_SHA -t my-image:latest .
    - docker push my-image:$CI_COMMIT_SHA
    - docker push my-image:latest
