name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SSH_USER: ${{ secrets.SSH_USER }}

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker build -t $DOCKER_USERNAME/tg-web-app:$GITHUB_SHA -t $DOCKER_USERNAME/tg-web-app:latest .
        docker push $DOCKER_USERNAME/tg-web-app:$GITHUB_SHA
        docker push $DOCKER_USERNAME/tg-web-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: push

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH and deploy
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" | ssh-add - # Добавляем приватный ключ
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $SSH_USER@$SERVER_IP "kubectl set image deployment/tg-web-app-deployment tg-web-app=$DOCKER_USERNAME/tg-web-app:$GITHUB_SHA --record"
